<a href="https://colab.research.google.com/github/2303a51729Ajaykumar/Application-of-Data-Mining/blob/main/Application_data_mining_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/patients.csv')

In [3]:
df.head()

   Patient_ID   Age  Glucose_Level  Blood_Pressure  Insulin        BMI
0         101  56.0          142.0            95.0    107.0        NaN
1         102  46.0          143.0            75.0    144.0  31.722504
2         103  33.0           79.0            92.0    195.0  31.572256
3         104  75.0          140.0            96.0     55.0  19.937204
4         105  70.0          115.0            83.0    152.0  29.576845

In [4]:
df.isnull().sum()

Patient_ID        0
Age               0
Glucose_Level     5
Blood_Pressure    5
Insulin           5
BMI               5
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      50 non-null     int64
 1   Age             50 non-null     float64
 2   Glucose_Level   45 non-null     float64
 3   Blood_Pressure  45 non-null     float64
 4   Insulin         45 non-null     float64
 5   BMI             45 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 2.5 KB

In [6]:
df.describe()

,Patient_ID,Age,Glucose_Level,Blood_Pressure,Insulin,BMI
count,50.00000,50.000000,45.000000,45.000000,45.000000,45.000000
mean,125.50000,55.440000,107.666667,106.177778,118.044444,27.128133
std,14.57738,14.071479,23.534308,22.660828,44.001010,5.031952
min,101.00000,30.000000,76.000000,62.000000,51.000000,19.094712
25%,113.25000,43.000000,88.000000,88.000000,82.000000,23.051127
50%,125.50000,57.500000,106.000000,109.000000,118.000000,27.078134
75%,137.75000,66.750000,132.000000,125.000000,154.000000,31.722504
max,150.00000,79.000000,146.000000,139.000000,195.000000,34.380741

In [7]:
df['Glucose_Level'].fillna(df['Glucose_Level'].mean(),inplace=True)

<ipython-input-7-5e2870616e36>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Glucose_Level'].fillna(df['Glucose_Level'].mean(),inplace=True)

In [9]:
df.isnull().sum()

Patient_ID        0
Age               0
Glucose_Level     0
Blood_Pressure    5
Insulin           5
BMI               5
dtype: int64

In [11]:
df['Blood_Pressure'].fillna(df['Blood_Pressure'].mean(),inplace=True)

<ipython-input-11-b128fce9611a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Blood_Pressure'].fillna(df['Blood_Pressure'].mean(),inplace=True)

In [12]:
df['Insulin'].fillna(df['Insulin'].mean(),inplace=True)

<ipython-input-12-c5ed9f3a2ce9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Insulin'].fillna(df['Insulin'].mean(),inplace=True)

In [13]:
df['BMI'].fillna(df['BMI'].mean(),inplace=True)

<ipython-input-13-a0e80e3532ba>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(df['BMI'].mean(),inplace=True)

In [14]:
df.isnull().sum()

Patient_ID        0
Age               0
Glucose_Level     0
Blood_Pressure    0
Insulin           0
BMI               0
dtype: int64

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:


  scaler = MinMaxScaler()

In [17]:
df[['Age', 'Glucose_Level']] = scaler.fit_transform(df[['Age', 'Glucose_Level']])

In [18]:
df['Blood_Pressure'] = (df['Blood_Pressure'] - df['Blood_Pressure'].min()) / (df['Blood_Pressure'].max() - df['Blood_Pressure'].min())

In [19]:
from sklearn.preprocessing import StandardScaler

s_scaler = StandardScaler()

In [20]:
df[['BMI']] = s_scaler.fit_transform(df[[ 'BMI']])

In [21]:
df['BMI']

0     0.000000
1     0.973303
2     0.941474
3    -1.523376
4     0.518752
5    -1.701855
6     0.702868
7    -0.872302
8     1.255091
9    -0.863701
10    0.000000
11   -0.376015
12   -1.418990
13    1.536443
14    0.899450
15    0.295983
16   -0.135977
17   -1.322359
18   -0.789847
19    1.362110
20    0.823433
21   -1.384140
22    1.284342
23    1.433392
24   -0.721635
25    1.460223
26   -0.010592
27    0.000000
28   -0.608536
29   -1.199781
30    0.036789
31    1.208040
32   -0.434920
33   -1.497850
34   -0.676935
35   -0.291238
36    0.335225
37   -1.540919
38   -0.618648
39   -1.579373
40    1.144858
41    0.000000
42   -0.300486
43    1.479725
44    1.071749
45    0.447509
46   -1.248919
47    1.485478
48    0.000000
49    0.422159
Name: BMI, dtype: float64

In [22]:
df['Insulin'] = (df['Insulin'] - df['Insulin'].mean()) / df['Insulin'].std()

In [23]:
df

    Patient_ID       Age  Glucose_Level  Blood_Pressure   Insulin       BMI
0          101  0.530612       0.942857        0.428571 -0.264882  0.000000
1          102  0.326531       0.957143        0.168831  0.622500  0.973303
2          103  0.061224       0.042857        0.389610  1.845649  0.941474
3          104  0.918367       0.914286        0.441558 -1.512014 -1.523376
4          105  0.816327       0.557143        0.272727  0.814366  0.518752
5          106  0.265306       0.471429        0.233766  0.000000 -1.701855
6          107  0.653061       0.342857        0.000000  0.310717  0.702868
7          108  0.244898       0.114286        0.935065  0.000000 -0.872302
8          109  0.612245       0.452381        0.519481  1.653782  1.255091
9          110  0.897959       0.428571        0.259740 -0.552682 -0.863701
10         111  0.653061       0.885714        0.573737  1.437932  0.000000
11         112  0.571429       0.071429        0.376623 -1.320148 -0.376015
12         113  0.836735       0.014286        0.987013  1.006233 -1.418990
13         114  0.000000       0.742857        0.961039 -1.559981  1.536443
14         115  0.510204       0.800000        0.935065 -0.480732  0.899450
15         116  0.183673       1.000000        0.233766 -1.535998  0.295983
16         117  0.204082       0.471429        0.779221 -0.960398 -0.135977
17         118  1.000000       0.185714        0.573737  0.142834 -1.322359
18         119  0.081633       0.300000        0.558442 -0.720565 -0.789847
19         120  0.510204       0.442857        1.000000  0.000000  1.362110
20         121  0.632653       0.114286        0.285714 -0.336832  0.823433
21         122  0.428571       0.714286        0.896104 -0.504715 -1.384140
22         123  0.938776       0.814286        0.753247  1.246066  1.284342
23         124  0.857143       0.452381        0.272727  0.694450  1.433392
24         125  0.571429       0.200000        0.688312 -0.864465 -0.721635
25         126  0.632653       0.528571        0.363636 -0.049033  1.460223
26         127  0.367347       0.100000        0.701299 -1.607947 -0.010592
27         128  0.265306       0.485714        0.610390  1.222083  0.000000
28         129  0.224490       0.914286        0.753247  0.000000 -0.608536
29         130  0.428571       0.314286        0.948052  0.166817 -1.199781
30         131  0.673469       0.985714        0.194805  0.190801  0.036789
31         132  0.795918       0.128571        0.961039 -0.001066  1.208040
32         133  0.673469       0.457143        0.701299  1.365983 -0.434920
33         134  0.755102       0.200000        0.636364 -0.360816 -1.497850
34         135  0.897959       0.942857        0.337662  1.533866 -0.676935
35         136  0.163265       0.000000        0.389610  0.958266 -0.291238
36         137  0.795918       0.452381        0.870130 -0.648615  0.335225
37         138  0.836735       0.885714        0.090909 -0.600649 -1.540919
38         139  0.000000       0.452381        0.818182  1.413949 -0.618648
39         140  0.448980       0.085714        0.573737 -1.344131 -1.579373
40         141  0.591837       0.171429        0.573737  0.334700  1.144858
41         142  0.551020       0.242857        0.051948 -1.272181  0.000000
42         143  0.326531       0.452381        0.573737 -1.200231 -0.300486
43         144  0.428571       0.228571        0.363636 -1.104298  1.479725
44         145  0.183673       0.014286        0.740260  0.000000  1.071749
45         146  0.632653       0.942857        0.948052  1.629799  0.447509
46         147  0.734694       0.371429        0.597403 -1.535998 -1.248919
47         148  0.000000       0.185714        0.883117  0.598517  1.485478
48         149  0.244898       0.042857        0.740260  0.862333  0.000000
49         150  1.000000       0.600000        0.740260  0.286734  0.422159